index:
    path: /
    controller: App\Controller\DefaultController::index

listCategories:
    path: /listCategories
    controller: App\Controller\CategoryController::listCategories

addCategory:
    path: /addCategory
    controller: App\Controller\CategoryController::addCategory

deleteCategory:
    path: /deleteCategory/{id}
    controller: App\Controller\CategoryController::deleteCategory

updateCategory:
    path: /updateCategory/{id}
    controller: App\Controller\CategoryController::updateCategory

listProducts:
    path: /listProducts
    controller: App\Controller\ProductController::listProducts

addProduct:
    path: /addProduct
    controller: App\Controller\ProductController::addProduct
    
deleteProduct:
    path: /deleteProduct/{id}
    controller: App\Controller\ProductController::deleteProduct

updateProduct:
    path: /updateProduct/{id}
    controller: App\Controller\ProductController::updateProduct