listCategories:
    path: /listCategories
    controller: App\Controller\CategoryController::listCategories

addCategory:
    path: /addCategory
    controller: App\Controller\CategoryController::addCategory

deleteCategory:
    path: /deleteCategory/{id}
    controller: App\Controller\CategoryController::deleteCategory

updateCategory:
    path: /updateCategory/{id}
    controller: App\Controller\CategoryController::updateCategory

listProducts:
    path: /listProducts
    controller: App\Controller\ProductController::listProducts

addProduct:
    path: /addProduct
    controller: App\Controller\ProductController::addProduct
    
deleteProduct:
    path: /deleteProduct/{id}
    controller: App\Controller\ProductController::deleteProduct

updateProduct:
    path: /updateProduct/{id}
    controller: App\Controller\ProductController::updateProduct

exportProducts:
    path: /exportProducts
    controller: App\Controller\ProductController::exportProducts

listSuppliers:
    path: /listSuppliers
    controller: App\Controller\SupplierController::listSuppliers

addSupplier:
    path: /addSupplier
    controller: App\Controller\SupplierController::addSupplier
    
deleteSupplier:
    path: /deleteSupplier/{id}
    controller: App\Controller\SupplierController::deleteSupplier

updateSupplier:
    path: /updateSupplier/{id}
    controller: App\Controller\SupplierController::updateSupplier

listOrders:
    path: /listOrders
    controller: App\Controller\OrderController::listOrders

addOrder:
    path: /addOrder
    controller: App\Controller\OrderController::addOrder
    
deleteOrder:
    path: /deleteOrder/{id}
    controller: App\Controller\OrderController::deleteOrder

updateOrder:
    path: /updateOrder/{id}
    controller: App\Controller\OrderController::updateOrder

exportOrders:
    path: /exportOrders
    controller: App\Controller\OrderController::exportOrders

addFacture:
    path: /addFacture/{id}
    controller: App\Controller\FactureController::addFacture

deleteFacture:
    path: /deleteFacture/{id}
    controller: App\Controller\FactureController::deleteFacture

exportFactures:
    path: /exportFactures
    controller: App\Controller\OrderController::exportFactures

login:
    path: /login
    controller: App\Controller\SecurityController::logout