index:
    path: /
    controller: App\Controller\DefaultController::index

listCategories:
    path: /listCategories
    controller: App\Controller\CategoryController::listCategories

addCategory:
    path: /addCategory
    controller: App\Controller\CategoryController::addCategory

deleteCategory:
    path: /deleteCategory/{id}
    controller: App\Controller\CategoryController::deleteCategory

products:
    path: /home
    controller: App\Controller\ProductController::home   